services:
  - type: web
    name: aniwatch-stremio
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
